### ISSUE TITLE
Testování K7 - přestalo fungovat přidávání DNNT labelů

### ISSUE THREAD

**Issue by hlavacekrene** [ceskaexpedice/kramerius#898]
Přestalo fungovat přidávání labelu dnnt. (před cca 14 dny bylo vše ok)
Label se zapíše do RELS-EXT, ale dál se už nespustí solr. 
Samotný solr funguje v pořádku (uuid: muzete reindexovat a výsledek je ok), 
ale v tom přidávání labelu dnnt to nenaváže, něco se tam nepředá. 
Pro otestování zkuste si vybrat náhodně některé uuid:   

uuid:0bb48d60-da7f-11e2-9923-005056827e52,
uuid:2fd95670-ab87-11ec-a3e4-5ef3fc9bb22f,
uuid:9cb37350-8983-11ec-8ca2-005056827e52,
uuid:2727f3a0-41f7-11ec-b757-005056827e51,
uuid:8a179060-ab56-11ec-8353-005056827e51,
uuid:da88b840-4baf-11e3-9c86-005056827e51,
uuid:d85d1b60-552c-11e4-8b11-005056827e51,
uuid:d831b520-406f-11e2-9b88-005056827e51,
uuid:6579bb90-f57b-11e9-9a61-005056827e52,
uuid:d803f1f0-aef1-11ea-998c-005056827e51,
uuid:18686920-3e27-11e4-bc3a-005056827e51,
uuid:8f945f10-86e0-11e5-a715-005056827e52,
uuid:807e2e10-cbbc-11e3-aec3-005056827e52,
uuid:f031f640-bb1b-11ec-bc43-005056827e52,
uuid:9ca11590-598f-11eb-b4d1-005056827e51,
uuid:65f8dd40-b404-11ec-b29b-005056827e52,
uuid:d8091830-7f76-11e3-a6e0-005056827e52,
uuid:d845a290-ebbf-11e3-b72e-005056827e52,
uuid:bcf6a980-df26-11e3-b110-005056827e51,
uuid:9a59c040-6825-11e5-9e57-005056827e52,
uuid:b6454040-8fbf-11ec-a3e4-5ef3fc9bb22f,
uuid:b1325df0-b3ea-11ec-8353-005056827e51,
uuid:4adc8e90-3d60-11e3-9c86-005056827e51,
uuid:658cb780-df52-11e3-b110-005056827e51,
uuid:09f5f3a0-12e0-11eb-9e0f-005056827e51,
uuid:27822c40-90a8-11eb-9316-005056827e51,
uuid:a3e7da10-2a3b-11eb-979b-005056827e52,
uuid:bc27bda0-fb51-11e2-9923-005056827e52,
uuid:5baf8250-50df-11eb-9496-005056827e52,
uuid:776e8a10-7518-11eb-9f97-005056827e51,
uuid:9d3acd10-b407-11ec-b29b-005056827e52,
uuid:3ad942b0-1db1-11e2-bec6-005056827e51,
uuid:e4d74700-a69e-11ec-8353-005056827e51     

a přidejte DNNTO. Solr nenaváže, nespustí se po zapsání do rels-ext.

**Comment by vlahoda** [comment]
To vypada, ze se spatne predava PID jako parametr procesu. V seznamu testovacich PIDu je uuid:d803f1f0-aef1-11ea-998c-005056827e51, ale proces je volan takto:
INFO: requesting url: http://localhost:8080/search//lr?action=updateName&uuid=4f7c76cc-426b-4afd-bbf9-eb8b128a5d3f&name=P%C5%99id%C3%A1n%C3%AD+licence+%27dnnto%27+pro+pid%3Auuid%3A803f1f0-aef1-11ea-998c-005056827e51

Tedy v uuid chybi prvni znak za dvojteckou.
Proces pak padne na tom, ze nenajde objekt s uuid:803f1f0-aef1-11ea-998c-005056827e51 v ulozisti.
@honza-rychtar @rzeh4n  - odhaduji, ze je to chyba v admin klientovi

**Comment by rzeh4n** [comment]
@vlahoda 
Myslím, že to spíš souvisí s procesem SetLicenseProcess, on se spustí a chvíli jede.
Možná to bude souviset se změnami ohledně logikou okolo sbírek, řešili jsme tam nějaké zámky kvůli transakcím.

Nasimuluju si to lokálně a ozvu se zítra odpoledne.

**Comment by rzeh4n** [comment]
Spojujeme tady více různých situací. 

Jedna věc je  nastavení licence pro objekt uuid:803f1f0-aef1-11ea-998c-005056827e51

**Comment by rzeh4n** [comment]
Jedna věc je pro objekt uuid:803f1f0-aef1-11ea-998c-005056827e51, třeba v procesu https://admin.k7-test.mzk.cz/processes/289701 a logy tady.
Tam je problém v tom, že objekt foxml v repozitáři neexistuje, ale v processing indexu o něm informace zůstaly, proto:

> Caused by: cz.incad.kramerius.fedora.om.RepositoryException: object not consistently found in storage: uuid:803f1f0-aef1-11ea-998c-005056827e51

Myslel jsem si, jestli to není naopak, tj. záznamy v processing indexu nekonzistentní s foxml, řešením by byl rebuild processing indexu pro konkrétní objekt. To ale padlo právě na neexistujícím foxml:
https://admin.k7-test.mzk.cz/processes/290123 

Proč soubor s foxml na disku není, to netuším.


Jiná situace třeba u uuid:0bb48d60-da7f-11e2-9923-005056827e52, tam je záznam v repozitáři v pořádku a děje se něco jiného, tam to vypadá na timeout ze strany solr během procesu přidávání licence.
https://admin.k7-test.mzk.cz/processes/290127

> Jun 17, 2022 9:34:14 AM cz.incad.kramerius.processes.starter.ProcessUpdatingChannel$StandardProcessUpdatingChannel updateName
INFO: requesting url: http://localhost:8080/search//lr?action=updateName&uuid=1d6441e5-480e-42c9-a71f-c7c837608e8b&name=P%C5%99id%C3%A1n%C3%AD+licence+%27dnnto%27+pro+pid%3Auuid%3A0bb48d60-da7f-11e2-9923-005056827e52
Jun 17, 2022 9:34:14 AM cz.incad.kramerius.SetLicenseProcess addLicense
INFO: Adding license 'dnnto' to uuid:0bb48d60-da7f-11e2-9923-005056827e52
Jun 17, 2022 9:34:14 AM cz.incad.kramerius.SetLicenseProcess addLicense
INFO: updating RELS-EXT record of the target object uuid:0bb48d60-da7f-11e2-9923-005056827e52
Jun 17, 2022 9:34:15 AM cz.incad.kramerius.SetLicenseProcess addRelsExtRelationAfterNormalization
INFO: relation 'license' already found in RELS-EXT of uuid:0bb48d60-da7f-11e2-9923-005056827e52
Jun 17, 2022 9:34:15 AM cz.incad.kramerius.SetLicenseProcess addLicense
INFO: updating RELS-EXT record of all (own) ancestors of the target object uuid:0bb48d60-da7f-11e2-9923-005056827e52
Jun 17, 2022 9:34:15 AM cz.incad.kramerius.SetLicenseProcess addLicense
INFO: updating search index for all (own) ancestors
Jun 17, 2022 9:34:15 AM cz.incad.kramerius.SetLicenseProcess addLicense
INFO: updating search index for the target object
Jun 17, 2022 9:34:15 AM cz.incad.kramerius.SetLicenseProcess addLicense
INFO: updating search index for all (own) descendants of target object
Jun 17, 2022 9:34:58 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:8983: The target server failed to respond
Jun 17, 2022 9:34:58 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:8983
Jun 17, 2022 9:34:58 AM cz.incad.kramerius.processes.starter.ProcessStarter main
SEVERE: null
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at cz.incad.kramerius.processes.starter.ProcessStarter.main(ProcessStarter.java:125)
Caused by: java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8983 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
at cz.incad.kramerius.SetLicenseProcess$PidsOfDescendantsProducer.next(SetLicenseProcess.java:577)
at cz.incad.kramerius.SetLicenseProcess.addLicense(SetLicenseProcess.java:162)
at cz.incad.kramerius.SetLicenseProcess.main(SetLicenseProcess.java:104)
... 5 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8983 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at cz.incad.kramerius.impl.SolrAccessImplNewIndex$SolrUtils.requestWithSelectReturningStream(SolrAccessImplNewIndex.java:288)
at cz.incad.kramerius.impl.SolrAccessImplNewIndex$SolrUtils.requestWithSelectReturningString(SolrAccessImplNewIndex.java:270)
at cz.incad.kramerius.impl.SolrAccessImplNewIndex$SolrUtils.requestWithSelectReturningJson(SolrAccessImplNewIndex.java:253)

Ten druhý případ ještě řeším.

**Comment by vlahoda** [comment]
Ano, druhy pripad je asi opravdu neco jineho. 

Ale ten prvni je zpusoben tim, ze se pri volani procesu nebo v jeho prubehu ztrati prvni znak z uuid. To uuid 803f1f0-aef1-11ea-998c-005056827e51 je nevalidni, v prvni skupine ma jen 7 znaku a ma jich tam byt 8. A je jinak naprosto identicke s uuid d803f1f0-aef1-11ea-998c-005056827e51, ktere @hlavacekrene  uvedl v seznamu nefunkcnich uuid.

**Comment by rzeh4n** [comment]
Ten druhý případ je způsobený tím, že Solr páchá sebevraždy přes solr_oom_killer.

Ten proces totiž posílá po dávkách (1000 záznamů v dávce) atomické updaty pro všechny potomky objektu, kterému se nastavuje licence. Jakože se přidává licenses_of_ancestors=L (zde L je "dnnto"). Takže teoreticky až tisíce updatů bez explicitního commitu.

Když jsem zvýšil paměť pro SOLR z 5 na 7 GB, už to prošlo. Konkrétně pro monografii uuid:0bb48d60-da7f-11e2-9923-005056827e52 s pouhými 154 stránkami. Přesto během toho paměť SOLR nabobtnala na nějakých 6.4 GB (po zvýšení limitu).

Překvapuje mě, že před zvýšením to bobtnalo až skoro do vyčerpání paměti, že se volal ten oom killer. Mohl bych ještě zmenšit ty dávky na třeba 100 záznamů v dávce, případně snížit čas bez commitu z aktuálních 15 sekund pro tyhle hromadné aktualizace.

**Comment by pavel-stastny** [comment]
@zabak @hlavacekrene   Předpokládám, že se jedná o starší situaci a toto se nyní neděje.  Uzavírám a v případě potřeby je možno znovu otevřít,
